In [1]:
import pandas as analytics
import numpy as maths
from numba import cuda , jit
import warnings 
warnings.filterwarnings("ignore")

In [2]:
df_data = analytics.read_csv('data1.csv',header = None , names = ['x0','x1','y'])
df_data

x0       x1  y
0    22.930 -20.9020  1
1    12.410   2.0033  1
2   -20.686 -33.3030  1
3    46.974 -13.5550  1
4    41.965  20.3680  1
..      ...      ... ..
195 -29.232  28.4410 -1
196 -10.159   7.3065 -1
197 -32.026  14.9380 -1
198 -49.533 -11.1280 -1
199 -26.065  33.4200 -1

[200 rows x 3 columns]

In [254]:
class neural_network :
    
    def __init__(self,df_data , number_of_neurons = [2,1], epsilon = 5e-2, alpha = 0.2, hidden_function = 'relu', output_function = 'sigmoid' , initialisation_technique = 'xavier_normal') :
        self.number_of_hidden_layers = len(number_of_neurons) - 1
        self.number_of_neurons = number_of_neurons
        self.df_data = df_data
        self.epsilon = epsilon 
        self.N = df_data.shape[0]
        self.alpha = alpha

        functions_list = {'relu':self.relu , 'sigmoid' : self.sigmoid , 'identity' : self.identity}
        intialisation_list = {'xavier_normal':self.xavier_normal , 'he_normal':self.he_normal, 'xavier_uniform' : self.xavier_uniform, 'he_uniform' : self.he_uniform, 'uniform' : self.uniform }
    
        self.hidden = functions_list[hidden_function]
        self.output = functions_list[output_function]
        self.initialise = intialisation_list[initialisation_technique]

        if self.output == self.sigmoid and self.number_of_neurons[-1] != 1 :
            raise ValueError('Sigmoid must have only one neuron in the output. Please check the structure !')

    def relu(self,x) :
        """Hidden Activation Function"""
        return max(0,x)
    
    def sigmoid(self,x):
        """Output Function"""
        return 1 / (1 + maths.exp(-x))

    def identity(self,x):
        return x

    def calculate_derivative(self, data, func):
        if func == self.relu :
            if data > 0 : data = 1
            derivative = func(data)

        if func == self.sigmoid :
            derivative = func(data) * ( 1- func(data))

        if func == self.identity :
            derivative = 1

        return derivative

    def xavier_normal(self,fan_in, fan_out):
        mu = 0 
        sigma = (2 / (fan_in + fan_out))**0/5

        weight = maths.random.normal(mu, sigma,(fan_out, fan_in))
        bias = maths.random.normal(mu,sigma,(fan_out,1))

        return weight , bias

    def he_normal(self,fan_in, fan_out):
        mu = 0
        sigma = (2/fan_in) ** 0.5
        
        weight = maths.random.normal(0,sigma,(fan_out,fan_in))
        bias = maths.random.normal(0,sigma,(fan_out,1))

        return weight , bias

    def xavier_uniform(self, fan_in, fan_out) :
        weight = maths.random.uniform(-( 6 ** 0.5 / (fan_in + fan_out)) ** 0.5 , (6 / (fan_in + fan_out)) ** 0.5, (fan_out,fan_in))
        bias = maths.random.uniform(-( 6 ** 0.5 / (fan_in + fan_out)) ** 0.5 , (6 / (fan_in + fan_out)) ** 0.5, (fan_out,1))

        return weight, bias
        
    def he_uniform(self, fan_in, fan_out) :
        weight = maths.random.uniform(-( 6 ** 0.5 / fan_in) ** 0.5 , (6 / fan_out) ** 0.5, (fan_out,fan_in))
        bias = maths.random.uniform(-( 6 ** 0.5 / fan_in) ** 0.5 , (6 / fan_out) ** 0.5, (fan_out,1))

        return weight, bias

    
    def uniform(self, fan_in, fan_out) :
        weight = maths.random.uniform(-1/fan_in**0.5 , 1/fan_in**0.5,(fan_out,fan_in))
        bias = maths.random.uniform(-1/fan_in**0.5 , 1/fan_in**0.5,(fan_out,1))

        return weight, bias
    
    
    def initialisation(self):
        weights = []
        bias = []
        for l in range(self.number_of_hidden_layers + 1):
            if l == 0 : previous_layer = df_data.shape[1] - 1
            else : previous_layer = self.number_of_neurons[l-1]
            present_layer = self.number_of_neurons[l]

            
            weight , bia = self.initialise(previous_layer , present_layer)    
            
            weights.append(weight)
            bias.append(bia)
        
        self.weights = weights
        self.bias = bias


    def forward_propagation(self,x):
        activations = []
        activations.append(x)   # inputdata point is the initial activation
        
        hidden_layers = []
        
        for l in range(self.number_of_hidden_layers):
            neurons = self.weights[l] @ activations[l] + self.bias[l]   # it actually should be activations[l+1] but because indexing in python starts from 0, so it is activations[l]
            activation = maths.matrix([self.hidden(float(neuron)) for neuron in neurons]).reshape(-1,1)
            hidden_layers.append(neurons)
            activations.append(activation)
   
        data = self.weights[-1] @ activations[-1] + self.bias[-1]
        outputs = maths.matrix([float(self.output(x)) for x in data]).reshape(-1,1)
        activations.append(outputs)
        
        self.hidden_layers = hidden_layers
        self.activations = activations


    def backward_propagation(self) :
      
        deltas = []
        diff_loss_wrt_output = self.activations[-1]

        data = self.weights[-1] @ self.activations[-2] + self.bias[-1]
        outputs = maths.matrix([float(self.calculate_derivative(x,self.output)) for x in data]).reshape(diff_loss_wrt_output.shape)
        delta = maths.multiply(diff_loss_wrt_output , outputs)   # change in loss wrt output layer
        deltas.append(delta)
        
        grad_weights = []
        grad_biases = []

        for l in range(self.number_of_hidden_layers , -1, -1 ): # it is actually running from Output layer to the first hidden layer. Due to indexing convention, loop starts from number_of_hidden_layers and goes till 0
            grad_weight = deltas[0] @ self.activations[l].T
            grad_bias = deltas[0]

            info_passed_to_weights = self.weights[l].T @ deltas[0]   # information from present layer passed on to the weights connecting present and previous layers 
            if maths.any(maths.isinf(info_passed_to_weights)) :
                raise ValueError("Infinite values encountered while passing information to weights")
            
            if l > 0 : layer = self.hidden_layers[l-1]
            else : layer = self.activations[0]

            change_in_neurons = maths.matrix([self.calculate_derivative(float(i),self.hidden) for i in layer ]).reshape(-1,1)  # change of neurons of the previous layer

            
            delta =  maths.multiply(info_passed_to_weights , change_in_neurons ).reshape(-1,1)      # changes in loss wrt the previous layer's neurons
            if maths.any(maths.isnan(delta)) :
                raise ValueError("NaN values encountered in delta")
            deltas.insert(0,delta)

            grad_weights.insert(0,grad_weight)
            grad_biases.insert(0,grad_bias)
    
        return grad_weights, grad_biases


    def has_converged(self, prev_weights, prev_bias) :
        self._converged = (maths.linalg.norm(maths.matrix(self.weights[0]) - maths.matrix(prev_weights[0])) < self.epsilon) and (maths.linalg.norm(maths.matrix(self.bias[0]) - maths.matrix(prev_bias[0])) < self.epsilon)


    def update_weights(self):
        
        prev_weights = [w + 1 for w in self.weights]
        prev_bias = [b + 1 for b in self.bias]
        
        self._converged = False
        
        while not self._converged:
            prev_weights = self.weights.copy()
            prev_bias = self.bias.copy()
            
            for m in range(self.N) :
                x = maths.matrix(self.df_data.iloc[m][:-1]).reshape(-1,1)
                y = self.df_data.iloc[m][-1]
                self.forward_propagation(x)
                self.grad_weights, self.grad_bias = self.backward_propagation()

                for l in range(self.number_of_hidden_layers + 1) :
                    self.weights[l] = self.weights[l] - self.alpha/self.N * self.grad_weights[l]
                    self.bias[l] = self.bias[l] - self.alpha/self.N * self.grad_bias[l]
                    
            
            self.has_converged(prev_weights, prev_bias)

In [265]:
neurons_in_each_layer = [2,3,1]
epsilon = 1e-3
alpha = 0.4
hidden_function = 'relu'
output_function = 'identity'
initialise_through = 'he_normal'


ann = neural_network(df_data ,
                     number_of_neurons = neurons_in_each_layer,
                     epsilon = epsilon,
                     alpha = alpha,
                     hidden_function = hidden_function,
                     output_function = output_function,
                     initialisation_technique = initialise_through
                    )

ann.initialisation()
ann.update_weights()

for i in range(len(neurons_in_each_layer)):
    print("LAYER",i+1)
    print("Weights")
    print(ann.weights[i])
    print("Bias")
    print(ann.bias[i].T)
    print()

LAYER 1
Weights
[[ 0.31144653  0.80263842]
 [-1.01593462  0.0770445 ]]
Bias
[[0.4639363  0.33717232]]

LAYER 2
Weights
[[-0.07821319 -1.57349576]
 [-1.51038135 -0.79894774]
 [-0.3943689  -1.18272686]]
Bias
[[1.1061024  0.7134764  0.00507234]]

LAYER 3
Weights
[[-0.0371518   1.24023568  0.20255921]]
Bias
[[-0.03406018]]

