In [1]:
import pandas as analytics
import numpy as maths
from numba import cuda , jit
import warnings 
from neural_network import neural_network
warnings.filterwarnings("ignore")

In [2]:
df_data = analytics.read_csv('../data/data1.csv',header = None)
df_data.columns = ['x'+str(i) for i in df_data.columns[:-1]] + ['y']
df_data

x0       x1  y
0    22.930 -20.9020  1
1    12.410   2.0033  1
2   -20.686 -33.3030  1
3    46.974 -13.5550  1
4    41.965  20.3680  1
..      ...      ... ..
195 -29.232  28.4410 -1
196 -10.159   7.3065 -1
197 -32.026  14.9380 -1
198 -49.533 -11.1280 -1
199 -26.065  33.4200 -1

[200 rows x 3 columns]

In [3]:
neurons_in_each_layer = [2,3,4,1]
epsilon = 1e-3
alpha = 0.0001
hidden_function = 'relu'
output_function = 'identity'
initialise_through = 'xavier_normal'
batch_size = 20
optimiser = 'adam'
gamma = 0.8


ann = neural_network(df_data ,
                     number_of_neurons = neurons_in_each_layer,
                     epsilon = epsilon,
                     alpha = alpha,
                     hidden_function = hidden_function,
                     output_function = output_function,
                     initialisation_technique = initialise_through, 
                     batch_size = batch_size,
                     optimiser = optimiser,
                     gamma = gamma
                    )

ann.initialisation()
ann.update_weights()

for i in range(len(neurons_in_each_layer)):
    print("LAYER",i+1)
    print("Weights")
    print(ann.weights[i])
    print("Bias")
    print(ann.bias[i].T)
    print()

LAYER 1
Weights
[[ 1.23792941 -1.61998118]
 [ 0.13151577 -0.14723563]]
Bias
[[ 0.26626057 -0.1090049 ]]

LAYER 2
Weights
[[-0.18722325  0.01663241]
 [-1.82319233 -0.12750874]
 [-0.18292286 -0.17480748]]
Bias
[[ 0.07570874  0.80090462 -0.23032639]]

LAYER 3
Weights
[[-0.44932453  0.12394985 -0.04041889]
 [-0.10603204 -0.78900236 -0.20249476]
 [ 0.1629887  -0.03143271 -0.14021988]
 [ 0.29630649 -0.95378067  0.11672707]]
Bias
[[-0.06551394  0.58206514  0.10045865 -0.09471739]]

LAYER 4
Weights
[[0.45563325 0.90169998 0.27292295 1.18111442]]
Bias
[[-0.40984566]]

